server:
  port: 9000

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  h2:
    console:
      enabled: true # h2-console jdbc:h2:mem:testdb sa/
#
#spring:
#  security:
#    oauth2:
#      authorizationserver:
#        client:
#          oidc-client:
#            registration:
#              client-id: "sample"
#              client-secret: "{noop}sample"
#              client-authentication-methods:
#                - "client_secret_basic"
#              authorization-grant-types:
#                - "authorization_code"
#                - "refresh_token"
#              redirect-uris:
#                - "http://127.0.0.1:8080/login/oauth2/code/sample"
#              post-logout-redirect-uris:
#                - "http://127.0.0.1:8080/"
#              scopes:
#                - "openid"
#                - "profile"
#            require-authorization-consent: true